sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t skyline7349/docker-react .

script:
  - docker run skyline7349/docker-react npm run test -- --coverage

  deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-west-2-734074135068"
    bucket_path: "docker-react"
    on:
      branch: master